tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'dtan4/dtan4'
tap 'homebrew/brewdler'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/fuse'
tap 'homebrew/python'
tap 'homebrew/science'
tap 'homebrew/versions'
tap 'homebrew/x11'
tap 'neovim/neovim'
tap 'railwaycat/emacsmacport'
tap 'sanemat/font'
tap 'wantedly/tools', 'git@github.com:wantedly/homebrew-tools'
cask 'java'
cask 'osxfuse'
cask 'xquartz'
brew 'libyaml'
brew 'gdbm'
brew 'openssl'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'gettext'
brew 'axel'
brew 'boost'
brew 'boost-build'
brew 'freetype'
brew 'fontconfig'
brew 'libffi'
brew 'pcre'
brew 'pixman'
brew 'cairo'
brew 'cmake'
brew 'colordiff'
brew 'ctags'
brew 'curl'
brew 'zeromq'
brew 'czmq'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'docker'
brew 'e2fsprogs'
brew 'eigen'
brew 'envchain'
brew 'ext2fuse'
brew 'lame'
brew 'x264'
brew 'xvid'
brew 'ffmpeg'
brew 'pkg-config'
brew 'gobject-introspection'
brew 'icu4c'
brew 'harfbuzz'
brew 'jpeg'
brew 'libtool'
brew 'pango'
brew 'fontforge'
brew 'gmp'
brew 'isl'
brew 'mpfr'
brew 'libmpc'
brew 'gcc'
brew 'gdrive'
brew 'little-cms2'
brew 'ghostscript'
brew 'ghq'
brew 'gibo'
brew 'git-cal'
brew 'go'
brew 'glide'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'gnupg'
brew 'gperftools'
brew 'graphicsmagick'
brew 'haskell-stack'
brew 'heroku'
brew 'hub'
brew 'ilmbase'
brew 'xz'
brew 'imagemagick'
brew 'iperf3'
brew 'iproute2mac'
brew 'jerm'
brew 'jo'
brew 'jp2a'
brew 'oniguruma'
brew 'jq'
brew 'jumanpp'
brew 'kops'
brew 'libevent'
brew 'libsodium'
brew 'libssh2'
brew 'lua'
brew 'mas'
brew 'mecab'
brew 'mecab-ipadic'
brew 'mercurial'
brew 'mysql'
brew 'n'
brew 'nmap'
brew 'node'
brew 'python3'
brew 'numpy', args: ['with-python3']
brew 'nvm'
brew 'nyancat'
brew 'openexr'
brew 'openmotif'
brew 'p7zip'
brew 'pandoc'
brew 'pcre2'
brew 'peco'
brew 'percona-toolkit'
brew 'pgbadger'
brew 'postgresql'
brew 'progress'
brew 'protobuf'
brew 'pv'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'ruby-build'
brew 'rbenv'
brew 'rbenv-binstubs'
brew 'rust'
brew 'sshfs'
brew 'terminal-notifier'
brew 'terraform'
brew 'the_platinum_searcher'
brew 'the_silver_searcher'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'vault'
brew 'vim', args: ['with-lua']
brew 'wget'
brew 'xpdf'
brew 'z'
brew 'zplug'
brew 'zsh'
brew 'dtan4/dtan4/ec2c'
brew 'homebrew/science/opencv'
brew 'homebrew/science/opencv3'
brew 'homebrew/science/r'
brew 'neovim/neovim/neovim', args: ['HEAD']
brew 'railwaycat/emacsmacport/emacs-mac', args: ['with-spacemacs-icon']
brew 'wantedly/tools/esnctl'
brew 'wantedly/tools/kube'
brew 'wantedly/tools/sap'
brew 'wantedly/tools/valec'
cask 'alfred'
cask 'android-studio'
cask 'arduino'
cask 'atom'
cask 'bettertouchtool'
cask 'colorpicker'
cask 'dash'
cask 'dropbox'
cask 'evernote'
cask 'gitify'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'gyazo'
cask 'insomniax'
cask 'intellij-idea'
cask 'iterm2'
cask 'keycastr'
cask 'licecap'
cask 'rescuetime'
cask 'rubymine'
cask 'skim'
cask 'skitch'
cask 'skype'
cask 'slack'
cask 'spectacle'
cask 'vagrant'
cask 'virtualbox'
mas 'ActivityTimer', id: 808647808
mas 'ASUS Firmware Restoration', id: 1020519014
mas 'Bear', id: 1091189122
mas 'Fluid Browser', id: 1077036385
mas 'GarageBand', id: 682658836
mas 'Helium', id: 1054607607
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
mas 'Kobito', id: 896624060
mas 'Maxthon', id: 804619114
mas 'Microsoft Remote Desktop', id: 715768417
mas 'Night Owl', id: 428834068
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Slack', id: 803453959
mas 'StuffIt Expander', id: 405580712
mas 'Tomato One', id: 907364780
mas 'Veertu', id: 1024069033
mas 'VideoCast', id: 876836699
mas 'Wantedly Chat', id: 1076860635
mas 'Xccello', id: 785109225
mas 'Xcode', id: 497799835
