tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "asdf"
brew "direnv"
brew "envchain"
brew "fzf"
brew "gh"
brew "ghq"
brew "goenv", args: ["HEAD"]
brew "jq"
brew "mas"
brew "neovim"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "the_platinum_searcher"
brew "tig"
brew "tmux"
brew "zplug"
brew "zsh"
cask "alfred"
cask "authy"
cask "bettertouchtool"
cask "dropbox"
cask "droplr"
cask "google-japanese-ime"
cask "iterm2"
cask "karabiner-elements"
cask "slack"
mas "Display Menu", id: 549083868
mas "Keynote", id: 409183694
mas "Meeter", id: 1510445899
mas "Xcode", id: 497799835
