tap "caskroom/cask"
tap "caskroom/versions"
tap "cema-sp/tap"
tap "dtan4/dtan4"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/python"
tap "homebrew/science"
tap "homebrew/versions"
tap "neovim/neovim"
tap "sanemat/font"
tap "wantedly/tools", "git@github.com:wantedly/homebrew-tools"
brew "libyaml"
brew "gdbm"
brew "readline"
brew "ansible"
brew "autoconf"
brew "awscli"
brew "boost"
brew "boost-build"
brew "caddy"
brew "fontconfig"
brew "gettext"
brew "libffi"
brew "cmake"
brew "curl"
brew "libgpg-error"
brew "libassuan"
brew "libksba"
brew "pth"
brew "dirmngr"
brew "docker"
brew "e2fsprogs"
brew "envchain"
brew "pkg-config"
brew "icu4c"
brew "jpeg"
brew "libtool"
brew "fontforge"
brew "gmp"
brew "isl"
brew "mpfr"
brew "gcc"
brew "gdb"
brew "ghq"
brew "go"
brew "glide"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "gperftools"
brew "gpg-agent"
brew "graphicsmagick"
brew "haskell-stack"
brew "heroku"
brew "hub"
brew "ilmbase"
brew "iperf3"
brew "iproute2mac"
brew "jerm"
brew "oniguruma"
brew "jq"
brew "kops"
brew "lame"
brew "libevent"
brew "libsodium"
brew "libssh2"
brew "libusb-compat"
brew "little-cms2"
brew "lua"
brew "mas"
brew "mruby"
brew "mysql"
brew "ndenv"
brew "neovim", args: ["HEAD"]
brew "nkf"
brew "nmap"
brew "nodebrew"
brew "xz"
brew "numpy", args: ["with-python3"]
brew "openexr"
brew "openmotif"
brew "pcre2"
brew "peco"
brew "percona-toolkit"
brew "pgbadger"
brew "postgresql"
brew "protobuf"
brew "pyenv-virtualenv"
brew "rbenv"
brew "rbenv-binstubs"
brew "reattach-to-user-namespace"
brew "rust"
brew "sshfs"
brew "terminal-notifier"
brew "the_platinum_searcher"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tree"
brew "vim", args: ["with-lua"]
brew "x264"
brew "xpdf"
brew "xvid"
brew "yarn"
brew "z"
brew "zplug"
brew "zsh"
brew "dtan4/dtan4/ec2c"
brew "dtan4/dtan4/k8sec"
brew "wantedly/tools/esnctl"
brew "wantedly/tools/kube"
brew "wantedly/tools/rid"
brew "wantedly/tools/sap"
brew "wantedly/tools/valec"
brew "wantedly/tools/valecjr"
cask "alfred"
cask "android-studio"
cask "atom"
cask "bettertouchtool"
cask "dash"
cask "dropbox"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "insomnia"
cask "intel-haxm"
cask "iterm2"
cask "java"
cask "licecap"
cask "minikube"
cask "rubymine"
cask "skitch"
cask "slack"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
mas "Bear", id: 1091189122
mas "Display Menu", id: 549083868
mas "Helium", id: 1054607607
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kobito", id: 896624060
mas "Lungo", id: 1263070803
mas "Slack", id: 803453959
mas "Tomato One", id: 907364780
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
